PATHS:
  DATA_FILE_PATH: path/to/data.csv
  TRAIN_FILE_PATH: path/to/train.csv
  TEST_FILE_PATH: path/to/test.csv
  MODEL_OUTPUT_ROOT_PATH: outputs/model/

PARAMS:
  MODEL_NAME: msmarco-distilbert-base-v3
  EPOCHS: 3
  TRAIN_BATCH_SIZE: 32
  EVALUATION_STEPS: 5

VARIABLES:
  TOP_K: 10