PATHS:
  RAW_DATA_PATH: data/raw/raw_data.csv
  GEN_QA_DATA_PATH: data/raw/gen_qa_data.csv
  TEST_DATA_PATH: data/raw/test_data.csv
  MNLI_FORMAT_DATA_PATH: data/raw/mnli_data.json
  GEN_QA_MODEL_OUTPUT_PATH: outputs/model/model_with_gen_q/
  MLM_MODEL_OUTPUT_PATH: outputs/model/model_mlm/

PARAMS:
  MODEL_NAME: sentence-transformers/msmarco-distilbert-cos-v5

VARIABLES:
  TOP_K: 10
