PATHS:
  RAW_DATA_PATH: path/to/data.csv
  MNLI_FORMAT_DATA_PATH: path/to/mnli_data.json
  GEN_QA_DATA_PATH: path/to/generated_questions.json
  TEST_DATA_PATH: path/to/test.csv
  GEN_QA_MODEL_OUTPUT_PATH: outputs/model/
  MLM_MODEL_OUTPUT_PATH: outputs/model/model_mlm/

PARAMS:
  MODEL_NAME: sentence-transformers/msmarco-distilbert-cos-v5

VARIABLES:
  TOP_K: 10
